### ISSUE TITLE
Enhancement: Include github link of a commit in tweet

### ISSUE THREAD

**Issue by pratraut** [infosec-us-team/Immunefi-Bug-Bounty-Programs-Unofficial#1]
Now in the tweet, its not including commit link of changes. It will be convenient for users if we can include a commit link like [https://github.com/infosec-us-team/Immunefi-Bug-Bounty-Programs-Unofficial/commit/main](https://github.com/infosec-us-team/Immunefi-Bug-Bounty-Programs-Unofficial/commit/main) in every tweet. User can directly visit that link and check what is been updated. It a lot more convenient, i think.

We can use `URL Shortener` if tweet character limit is a concern.

**Comment by infosec-us-team** [comment]
Great suggestion.

Always tweeting a link to [main](https://github.com/infosec-us-team/Immunefi-Bug-Bounty-Programs-Unofficial/commit/main) is a lazy solution because even old tweets will be pointing to the latest commit, which will contain information not related to the content of the tweet you just clicked.

An update will be released today that makes every tweet include a link to the exact commit, that the content of the tweet references.

Thank you very much for your suggestion, was awesome.
